baseURL = "https://releases-qa.aspose.com"

languageCode = "en-us"
title = "Releases - aspose.com"
theme =  "downloads-common-theme"
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreErrors = ["error-disable-taxonomy"]

################################# Localization #########################
# Disabled languages
disableLanguages = []
defaultContentLang = 'en'
[languages]
    [languages.en]
      contentDir = 'content/en'
      languageName = "English"
      languageCode = "en"
      flag = "flag-us"
      weight = 1
      menuCode = "aspose-en"
    [languages.de]
      contentDir = 'content/de'
      languageName = "Deutsch"
      languageCode = "de"
      flag = "flag-de"
      weight = 2
      menuCode = "aspose-de"
################################# Localization #########################

[params]
    # googleAnalytics = ""
    # googletagmanager = ""
     backendURL = "https://releases.admin.aspose.com"
     dynamicmenuid = "aspose-en"
     faviconfolder = "aspose"
     contentsection = "com"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[outputs]
  home= ["HTML", "JSON"]

[deployment]

[[deployment.targets]]
name = "Stage"
URL = "s3://releases-qa.aspose.com/?region=us-west-2"

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^.+\\.(xml)$"
contentType = "application/xml"
gzip = true
force = true      