baseURL = "https://releases.aspose.com"

languageCode = "en-us"
title = "Releases - aspose.com"
theme =  "downloads-common-theme"
enableRobotsTXT = true
ignoreErrors = ["error-disable-taxonomy"]
timeout = 2400000

################################# Localization #########################
# Disabled languages
disableLanguages = []
defaultContentLang = 'en'
[languages]
    [languages.en]
      contentDir = 'content/en'
      languageName = "English"
      languageCode = "en"
      flag = "flag-us"
      weight = 1
      menuCode = "aspose-en"
    [languages.de]
      contentDir = 'content/de'
      languageName = "Deutsch"
      languageCode = "de"
      flag = "flag-de"
      weight = 2
      menuCode = "aspose-de"
    [languages.fr]
      contentDir = 'content/fr'
      languageName = "Français"
      languageCode = "fr"
      flag = "flag-fr"
      weight = 3
      menuCode = "aspose-fr"
    [languages.ru]
      contentDir = 'content/ru'
      languageName = "Русский"
      languageCode = "ru"
      flag = "flag-ru"
      weight = 4
      menuCode = "aspose-ru"
    [languages.zh]
      contentDir = 'content/zh'
      languageName = "简体中文"
      languageCode = "zh"
      flag = "flag-cn"
      weight = 5
      menuCode = "aspose-zh"
    [languages.ja]
      contentDir = 'content/ja'
      languageName = "日本"
      languageCode = "ja"
      flag = "flag-jp"
      weight = 6
      menuCode = "aspose-ja"
    [languages.pt]
      contentDir = 'content/pt'
      languageName = "Português"
      languageCode = "pt"
      flag = "flag-pt"
      weight = 7
      menuCode = "aspose-pt"
    [languages.el]
      contentDir = 'content/el'
      languageName = "Ελληνικά"
      languageCode = "el"
      flag = "flag-gr"
      weight = 8
      menuCode = "aspose-el"
    [languages.es]
      contentDir = 'content/es'
      languageName = "Español"
      languageCode = "es"
      flag = "flag-es"
      weight = 9
      menuCode = "aspose-es"
    [languages.id]
      contentDir = 'content/id'
      languageName = "Indonesia"
      languageCode = "id"
      flag = "flag-id"
      weight = 10
      menuCode = "aspose-id"
    [languages.tr]
      contentDir = 'content/tr'
      languageName = "Türkçe"
      languageCode = "tr"
      flag = "flag-tr"
      weight = 11
      menuCode = "aspose-tr"
################################# Localization #########################

[params]
    # googleAnalytics = ""
     googletagmanager = "GTM-NJMHSH"
     backendURL = "https://releases.admin.aspose.com"
     dynamicmenuid = "aspose-en"
     faviconfolder = "aspose"
     contentsection = "com"
     env = "production"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home= ["HTML", "JSON"]

[deployment]

[[deployment.targets]]
name = "Prod"
URL = "s3://releases.aspose.com/?region=us-west-2"
# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E2OKSF10F8M6Y4"


[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^.+\\.(xml)$"
contentType = "application/xml"
gzip = true
force = true
