# This is a basic workflow to help you get started with Actions

name: Staging3d
env:
    product_family: "3d"
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ stage ]
    paths:
       - 'content/english/3d/**'
  pull_request:
    branches: [ stage ]

  repository_dispatch:
    types: [staging-complete]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      product_family: "3d"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Remove unwanted folders
      run: |
        find ./content -mindepth 1 ! -regex '^./content/(/.*\)/3d\(/.*\)?' -delete
        ls content/ -all;
    - name: Build 3d pages
      run: hugo --config "./config-stage-releases-aspose-com.toml" -b "https://releases-qa.aspose.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify
      
    - name: Prepare public folder
      run: |
        mv public/sitemap.xml public/$product_family.xml;
        rm public/index.html;
        mkdir public_home;
        mkdir public_home/sitemaps;
        mv public/$product_family.xml public_home/sitemaps/;
        #ls public -all;
        ls public/zh -all;
        #ls public_home -all;
        
    - name: Upload family sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public_home/sitemaps/3d.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'sitemaps'

    - name: Upload default language
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/3d'
        DEST_DIR: '3d' 
        
    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/en/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/3d'
        
    - name: Upload zh folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/zh/3d'
        DEST_DIR: 'zh/3d' 

    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/zh/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/3d'

    - name: Upload ru folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ru/3d'
        DEST_DIR: 'ru/3d'  

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/ru/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/3d'
        
    - name: Upload fr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fr/3d'
        DEST_DIR: 'fr/3d'    

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/fr/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/3d'
        
    - name: Upload es folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2' 
        SOURCE_DIR: 'public/es/3d'
        DEST_DIR: 'es/3d' 

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/es/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/3d'

    - name: Upload de folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/de/3d'
        DEST_DIR: 'de/3d'  

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/de/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/3d'

    - name: Upload ja folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ja/3d'
        DEST_DIR: 'ja/3d'  

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/ja/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/3d'

    - name: Upload ko folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'releases-qa.aspose.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ko/3d'
        DEST_DIR: 'ko/3d'  

    - name: Upload ko sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'releases-qa.aspose.com'
        file_path: 'public/ko/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ko/3d'